# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SstRHhXrg0U9LJlfhmWMmm3oV19FDLIN
"""

import pandas as pd

df= pd.read_csv('/content/dataset.csv')

df.info

df= pd.read_csv('/content/Salary Data.csv')

df.info()

df.isnull().sum()

"""### Handling Missing Values

I will now impute the missing values in the DataFrame. Numerical columns will be filled with their mean, and categorical columns will be filled with their mode.
"""

# Separate numerical and categorical columns
numerical_cols = df.select_dtypes(include=['number']).columns
categorical_cols = df.select_dtypes(include=['object', 'category']).columns

# Impute numerical columns with the mean
for col in numerical_cols:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mean())

# Impute categorical columns with the mode
for col in categorical_cols:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mode()[0])

# Verify that there are no more null values
print("Null values after imputation:")
display(df.isnull().sum())

df.isnull().sum()

df.info()

"""### Separating Dependent and Independent Variables

I will now separate the DataFrame into independent variables (features), denoted as `X`, and the dependent variable (target), denoted as `y`. In this case, 'Salary' will be treated as the dependent variable.
"""

# Separate the dependent (target) and independent (features) variables
X = df.drop('Salary', axis=1)
y = df['Salary']

print("Shape of independent variables (X):")
print(X.shape)
print("\nShape of dependent variable (y):")
print(y.shape)

print("\nFirst 5 rows of independent variables (X):")
display(X.head())
print("\nFirst 5 rows of dependent variable (y):")
display(y.head())

"""### One-Hot Encoding for Categorical Features

To prepare the categorical features for machine learning models, I will apply one-hot encoding to the 'Gender', 'Education Level', and 'Job Title' columns in the independent variables `X`.
"""

X = pd.get_dummies(X, columns=['Gender', 'Education Level', 'Job Title'], drop_first=True)

print("Shape of independent variables (X) after one-hot encoding:")
print(X.shape)

print("\nFirst 5 rows of independent variables (X) after one-hot encoding:")
display(X.head())

"""### Splitting Data into Training and Testing Sets

To evaluate the performance of our machine learning model effectively, I will split the preprocessed data (`X` and `y`) into training and testing sets. This ensures that the model is trained on one subset of the data and tested on an independent subset, providing an unbiased assessment of its generalization capabilities.
"""

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets (e.g., 80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

"""### Feature Scaling

To ensure that all features contribute equally to the model training and to prevent features with larger values from dominating those with smaller values, I will apply feature scaling. Specifically, I will use `StandardScaler` to standardize the independent variables (`X_train` and `X_test`).
"""

from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform both training and testing data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("First 5 rows of X_train after scaling:")
display(pd.DataFrame(X_train_scaled, columns=X_train.columns).head())

print("\nFirst 5 rows of X_test after scaling:")
display(pd.DataFrame(X_test_scaled, columns=X_test.columns).head())

"""### Linear Regression Model

I will now build and train a Linear Regression model using the scaled training data. After training, I will make predictions on the test set and evaluate the model's performance using metrics such as Mean Absolute Error (MAE), Mean Squared Error (MSE), and R-squared.
"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Initialize the Linear Regression model
linear_reg_model = LinearRegression()

# Train the model using the scaled training data
linear_reg_model.fit(X_train_scaled, y_train)

# Make predictions on the scaled test data
y_pred_linear_reg = linear_reg_model.predict(X_test_scaled)

# Evaluate the model
mae_linear_reg = mean_absolute_error(y_test, y_pred_linear_reg)
mse_linear_reg = mean_squared_error(y_test, y_pred_linear_reg)
rmse_linear_reg = mse_linear_reg**0.5
r2_linear_reg = r2_score(y_test, y_pred_linear_reg)

print("Linear Regression Model Performance:")
print(f"Mean Absolute Error (MAE): {mae_linear_reg:.2f}")
print(f"Mean Squared Error (MSE): {mse_linear_reg:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_linear_reg:.2f}")
print(f"R-squared (R2): {r2_linear_reg:.2f}")

"""### Decision Tree Regression Model

Next, I will implement a Decision Tree Regressor. This model captures non-linear relationships and is interpretable. I will train it on the scaled data and evaluate its performance.
"""

from sklearn.tree import DecisionTreeRegressor

# Initialize the Decision Tree Regressor model
decision_tree_model = DecisionTreeRegressor(random_state=42)

# Train the model
decision_tree_model.fit(X_train_scaled, y_train)

# Make predictions
y_pred_decision_tree = decision_tree_model.predict(X_test_scaled)

# Evaluate the model
mae_dt = mean_absolute_error(y_test, y_pred_decision_tree)
mse_dt = mean_squared_error(y_test, y_pred_decision_tree)
rmse_dt = mse_dt**0.5
r2_dt = r2_score(y_test, y_pred_decision_tree)

print("Decision Tree Regression Model Performance:")
print(f"Mean Absolute Error (MAE): {mae_dt:.2f}")
print(f"Mean Squared Error (MSE): {mse_dt:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_dt:.2f}")
print(f"R-squared (R2): {r2_dt:.2f}")

"""### Random Forest Regression Model

Now, I will build a Random Forest Regressor, an ensemble learning method that combines multiple decision trees to improve predictive accuracy and control overfitting. The model will be trained on the scaled training data and evaluated.
"""

from sklearn.ensemble import RandomForestRegressor

# Initialize the Random Forest Regressor model
random_forest_model = RandomForestRegressor(random_state=42)

# Train the model
random_forest_model.fit(X_train_scaled, y_train)

# Make predictions
y_pred_random_forest = random_forest_model.predict(X_test_scaled)

# Evaluate the model
mae_rf = mean_absolute_error(y_test, y_pred_random_forest)
mse_rf = mean_squared_error(y_test, y_pred_random_forest)
rmse_rf = mse_rf**0.5
r2_rf = r2_score(y_test, y_pred_random_forest)

print("Random Forest Regression Model Performance:")
print(f"Mean Absolute Error (MAE): {mae_rf:.2f}")
print(f"Mean Squared Error (MSE): {mse_rf:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_rf:.2f}")
print(f"R-squared (R2): {r2_rf:.2f}")

"""### Support Vector Machine (SVM) Regression Model

Next, I will implement a Support Vector Machine (SVM) for regression, specifically `SVR`. This model is effective in high-dimensional spaces and cases where the number of dimensions is greater than the number of samples. I will train it on the scaled data and evaluate its performance.
"""

from sklearn.svm import SVR

# Initialize the Support Vector Regressor model
svm_model = SVR()

# Train the model
svm_model.fit(X_train_scaled, y_train)

# Make predictions
y_pred_svm = svm_model.predict(X_test_scaled)

# Evaluate the model
mae_svm = mean_absolute_error(y_test, y_pred_svm)
mse_svm = mean_squared_error(y_test, y_pred_svm)
rmse_svm = mse_svm**0.5
r2_svm = r2_score(y_test, y_pred_svm)

print("Support Vector Machine (SVM) Regression Model Performance:")
print(f"Mean Absolute Error (MAE): {mae_svm:.2f}")
print(f"Mean Squared Error (MSE): {mse_svm:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_svm:.2f}")
print(f"R-squared (R2): {r2_svm:.2f}")

"""### K-Nearest Neighbors (KNN) Regression Model

Finally, I will implement a K-Nearest Neighbors (KNN) Regressor. This non-parametric method uses the 'k' closest data points in the training set to predict the value of a new data point. I will train it on the scaled data and evaluate its performance.
"""

from sklearn.neighbors import KNeighborsRegressor

# Initialize the K-Nearest Neighbors Regressor model
knn_model = KNeighborsRegressor()

# Train the model
knn_model.fit(X_train_scaled, y_train)

# Make predictions
y_pred_knn = knn_model.predict(X_test_scaled)

# Evaluate the model
mae_knn = mean_absolute_error(y_test, y_pred_knn)
mse_knn = mean_squared_error(y_test, y_pred_knn)
rmse_knn = mse_knn**0.5
r2_knn = r2_score(y_test, y_pred_knn)

print("K-Nearest Neighbors (KNN) Regression Model Performance:")
print(f"Mean Absolute Error (MAE): {mae_knn:.2f}")
print(f"Mean Squared Error (MSE): {mse_knn:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_knn:.2f}")
print(f"R-squared (R2): {r2_knn:.2f}")

"""### All Regression Models in a Single Loop

To consolidate the model training and evaluation, I will now implement all the regression models within a single code block, iterating through them and printing their performance metrics. This approach enhances code reusability and simplifies comparison.
"""

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import pandas as pd

# Define the models to train
models = {
    'Linear Regression': LinearRegression(),
    'Decision Tree': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(random_state=42),
    'Support Vector Machine': SVR(),
    'K-Nearest Neighbors': KNeighborsRegressor()
}

# Dictionary to store performance metrics
performance_metrics = {}

# Loop through each model, train, predict, and evaluate
for name, model in models.items():
    print(f"\n--- Training {name} ---")

    # Train the model
    model.fit(X_train_scaled, y_train)

    # Make predictions
    y_pred = model.predict(X_test_scaled)

    # Evaluate the model
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = mse**0.5
    r2 = r2_score(y_test, y_pred)

    # Store metrics
    performance_metrics[name] = {
        'MAE': mae,
        'MSE': mse,
        'RMSE': rmse,
        'R2': r2
    }

    # Print performance
    print(f"{name} Model Performance:")
    print(f"  Mean Absolute Error (MAE): {mae:.2f}")
    print(f"  Mean Squared Error (MSE): {mse:.2f}")
    print(f"  Root Mean Squared Error (RMSE): {rmse:.2f}")
    print(f"  R-squared (R2): {r2:.2f}")

print("\n--- Summary of All Model Performances ---")
performance_df = pd.DataFrame(performance_metrics).T
display(performance_df)

"""### Visualizing Model Performance

To visually compare the performance of all the trained regression models, I will create bar plots for each evaluation metric (MAE, MSE, RMSE, and R2). This will provide a clear overview of which models performed best across different metrics.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set a style for the plots
sns.set_style('whitegrid')

# Create a figure with subplots for each metric
fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(16, 12))
axes = axes.flatten()

metrics = ['MAE', 'MSE', 'RMSE', 'R2']
colors = sns.color_palette('viridis', n_colors=len(performance_df))

for i, metric in enumerate(metrics):
    sns.barplot(x=performance_df.index, y=performance_df[metric], ax=axes[i], palette=colors)
    axes[i].set_title(f'{metric} for Each Model', fontsize=14)
    axes[i].set_xlabel('Model', fontsize=12)
    axes[i].set_ylabel(metric, fontsize=12)
    axes[i].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

"""### Saving the Best Model

Based on the performance metrics, the Random Forest Regressor achieved the highest R-squared score (0.89), indicating it is the best performing model among those evaluated. I will now save this model to a file in `pkl` format, which can be easily reloaded and used for future predictions.
"""

import pickle

# Identify the best model based on R2 score from the performance_metrics dictionary
best_model_name = max(performance_metrics, key=lambda k: performance_metrics[k]['R2'])
best_model = models[best_model_name]

# Define the filename for the saved model
model_filename = 'best_model.pkl'

# Save the best model to a .pkl file
with open(model_filename, 'wb') as file:
    pickle.dump(best_model, file)

print(f"The best model ('{best_model_name}') has been saved to '{model_filename}'")

